### ISSUE TITLE
Add: Config options to make farming Withers harder

### ISSUE THREAD

**Issue by James103** [orlouge/no-mob-farms#5]
Currently, a player can, with the right setup, continuously and automatically farm Withers as long as they have Soul Sand and Wither Skeleton Skulls. Not all servers may want players letting loose dozens of Withers or every player having hundreds of Nether Stars as a result of such a farm.

### Wither Farm Countermeasures

`wither_phase_through_bedrock=true`: Allows Withers to phase through (instead of destroying) Bedrock and similar unbreakable blocks.

`wither_spawn_collision_check=true`: Prevents new Withers from spawning when a non-player entity or block not part of the spawning structure is within a 3x3x4 area starting from the "feet" of the Wither and extending upward. Also prevents Dispensers from automatically spawning new Withers.

`wither_requires_sky_access=true`: Prevents new Withers from spawning unless the Wither to be spawned has sky access, thereby encouraging players to fight it "the intended way".

**Comment by orlouge** [comment]
Allowing Withers to phase through Bedrock is an invasive change for an issue that is better addressed by disabling bedrock and portal breaking, and carpet-fixes already does that.
As for the other two changes, I don't think they're necessary unless there's some Wither farm design that doesn't involve bedrock/portal breaking. Spawning a Wither in a small room sure makes the fight easier, but this is an AI issue, the Wither is supposed to be able to break outside of it and I'm not sure how to address that. The collision check is going to be either too conservative, like in your case, which makes it easy to elude, or too invasive (imagine not being able to spawn a Wither just because of a few blocks that wouldn't stop the Wither anyway). Also the Wither already breaks those blocks around it when it's summoned, unless it's bedrock. The sky access check is also invasive because it prevents Withers from being spawned in the Nether (other than on top of the roof, where you're not supposed to go anyway).

**Comment by James103** [comment]
At the very least, would it be possible to only allow players (and not Dispensers) to spawn new Withers? In other words, a Dispenser placing a wither skeleton skull should _never_ spawn a Wither when the relevant config option is enabled.

**Comment by James103** [comment]
Closing as "won't implement", but the idea to allow Withers to break blocks underneath themselves (as originally proposed and implemented in Progressive Bosses for Forge) will be posted here soon.
